MTES-MCT/Docurba

components/VTownAutocomplete.vue, package-lock.json, pages/pacsec.vue, pages/pacsec/geobretagne.vue, plugins/daturba.js, server-middleware/communes.js, server-middleware/geoide.js
Jette un oeil, nottament au endpoint communes
=> Geobretagne

components/Data/GeorisquesTable.vue, components/Data/INPNTable.vue, components/DataSourceCard.vue, components/DataSourcesList.vue, components/GeoIDECardList.vue, components/PAC/Sections/DataAttachmentsCards.vue, components/PAC/Sections/DataAttachmentsDialog.vue, components/PAC/Sections/FileAttachmentsDialog.vue
- prise en compte des retours QA
- ajout de tooltips
- fix: ajout de données sur les PLUi
- fix: afficher message données indisponibles pour les régions sans base territoriale
- reste à faire: ajout des liens vers les données dans le PDF
=> fix: attachments intercommunalité

components/Data/GeorisquesTable.vue, pages/collectivites/_collectiviteId.vue, pages/collectivites/_collectiviteId/donnees/georisques.vue, pages/collectivites/_collectiviteId/donnees/gpu.vue, pages/collectivites/_collectiviteId/donnees/inpn.vue
- adapt data components to new model
- fix georisques with new query param
- gpu: use our own geo center service
=> fix: data components & new model

pages/frise/_procedureId/index.vue
ref https://github.com/MTES-MCT/Docurba/issues/941
Remplace temporairement le formulaire de retours sur la feuille de route.
=> Formulaire de retours sur le partage

layouts/ddt.vue
Nous utilisons [une nouvelle interface](https://github.com/MTES-MCT/Docurba/issues/817) en 2024.
Le code pourra être [supprimé dans un second temps](https://github.com/MTES-MCT/Docurba/issues/923)
ref https://github.com/MTES-MCT/Docurba/issues/873
=> Désactivation de la validation de procédures 2023

.github/workflows/sudocuh_import.yml, daily_dump/common.mjs, daily_dump/database_config.mjs, daily_dump/index.mjs, daily_dump/steps/1-downloadDump.mjs, daily_dump/steps/4-interTablesToDocurbaPlan.mjs, daily_dump/steps/5-interTablesToDocurbaScot.mjs, daily_dump/steps/linkProceduresSecs.mjs, daily_dump/steps/sqlRunner.mjs
- Programmé tous les jours à 18h10 UTC ou à la demande (mais en obligeant à n'en avoir qu'un seul qui tourne à la fois)
- Adaptation pour qu'il aille chercher le dernier dump uploadé
- Écrits les points clefs dans le job summary via `appendToGithubSummary`
- Publie les CSV en tant qu'artefact
- Remplacement de l'utilisation de `pg_secret_config.mjs` par des variables d'environnements qui viennent de secrets Github
ref https://github.com/MTES-MCT/Docurba/issues/893
=> Import - Programmer sur Github Actions

.github/workflows/sudocuh_import.yml
ref https://github.com/MTES-MCT/Docurba/issues/893
=> Import - Passons les secrets dans l'environnement

daily_dump/common.mjs, daily_dump/steps/5-interTablesToDocurbaScot.mjs
Et correction d'une typo
ref https://github.com/MTES-MCT/Docurba/issues/893
=> Import - Saut de ligne après chaque message du résumé

pages/frise/_procedureId/index.vue
=> Message informatif sur une procédure inexistante

.github/workflows/sudocuh_import.yml, pages/ddt/_departement/collectivites/_collectiviteId/commune.vue, pages/ddt/_departement/collectivites/_collectiviteId/epci.vue
Nouvelle explication pour les DDT.
=> Import - Lancement le matin

nuxt.config.js, pages/ddt/_departement/collectivites/index.vue, plugins/enquete.js, sql/rpc/validated_collectivites_2024.sql
=> Validation de l'enquête 2024

package.json
ref https://github.com/MTES-MCT/Docurba/issues/888
=> Configuration pour déploiement Scalingo

pages/ddt/_departement/collectivites/index.vue
Plutôt que de coder notre propre mécanisme de sélection, utilisons l'API fournie par `<v-data-table>`.
Notre code était buggué sous Firefox.
ref https://github.com/MTES-MCT/Docurba/issues/817
=> Validation 2024 - Utilisation de la sélection de v-data-table

assets/data/events/SCOT_events.json
En attendant un affinage de ce qu'on propose, rendons les tous disponibles.
ref https://github.com/MTES-MCT/Docurba/issues/1068
=> SCoT - Tous les évènements disponibles à la création

assets/data/events/SCOT_events.json
Les suggestions n'étant pas correctes, on préfère les désactiver le temps de pouvoir les retravailler.
ref https://github.com/MTES-MCT/Docurba/issues/1077
=> SCoT - On ne suggère plus d'événements

nuxt.config.js, pages/frise/_procedureId/index.vue
fix https://github.com/MTES-MCT/Docurba/issues/930
=> Retrait du feature flag ACTIVE_DGD

pages/ddt/_departement/collectivites/index.vue
ref https://github.com/MTES-MCT/Docurba/issues/556
=> Mes collectivités - Les SD sont rangés avec les SCoT

components/SignalementProbleme.vue, pages/collectivites/_collectiviteId/index.vue, pages/ddt/_departement/collectivites/_collectiviteId/commune.vue, pages/ddt/_departement/collectivites/_collectiviteId/epci.vue, pages/frise/_procedureId/index.vue
fix https://github.com/MTES-MCT/Docurba/issues/1064
=> Ajout d'un formulaire "Signaler un problème"

pages/ddt/_departement/collectivites/index.vue
fix https://github.com/MTES-MCT/Docurba/issues/1091
=> Enquête - Les users peuvent annuler leur validation

pages/frise/_procedureId/index.vue
ref https://github.com/MTES-MCT/Docurba/issues/1034
=> Frise - Désactiver les modifications sur les frises archivées

pages/ddt/_departement/procedures/index.vue
ref https://github.com/MTES-MCT/Docurba/issues/653
=> Mes procédures - Plus de types de documents visibles et filtrables

pages/ddt/_departement/procedures/index.vue, tests_e2e/test_titre_procedure.py
Cassé par d5b9f42d
- Test utilise la recherche sur cette page pour confirmer la correction et accélérer le test (plus besoin d'afficher toutes les procédures)
fix https://github.com/MTES-MCT/Docurba/issues/1125
=> Mes procédures - Réparer la recherche

components/Frise/EventCard.vue
fix https://github.com/MTES-MCT/Docurba/issues/1129
=> Analytics pour le téléchargement de pièce jointe

plugins/enquete.js
ref https://github.com/MTES-MCT/Docurba/issues/1104
=> Validation des collectivités n'ayant pas de procédures en cours ou opposable

components/Dashboard/DUModalPerimetre.vue
Utilise le même vocabulaire que lors de la création de la procédure
ref https://github.com/MTES-MCT/Docurba/commit/ad6e103dde086951c175b4d397640af9a3036830
=> Wording Périmètre

content/Dev/API/urba/communesCode.md, content/Dev/API/urba/gpuMaillages.md, content/Dev/API/urba/gpuParente.md, content/Dev/API/urba/perimetres.md, content/Dev/API/urba/scots.md
fix https://github.com/MTES-MCT/Docurba/issues/1138
=> API - Documenter le nom de domaine des routes

nuxt/nuxt.config.js, nuxt/pages/ddt/_departement/collectivites/index.vue
fix https://github.com/MTES-MCT/Docurba/issues/1188
=> Disponibilité de l'enquête par DDT

nuxt/server-middleware/auth.js
Cela permet de se connecter en tant que collectivité dans tous les environnements.
=> APP_URL est utilisé pour la création du lien de connexion

nuxt/pages/ddt/_departement/pac.vue
Sur la page Mes PAC
ref https://github.com/MTES-MCT/Docurba/issues/1131
=> Transfert Repo PAC - Bandeau d'information utilisateur·ices

nuxt/server-middleware/urba.js
fix https://github.com/MTES-MCT/Docurba/issues/1213
=> API GPU - Ne pas exposer les EPCI sans compétences

nuxt/pages/ddt/_departement/collectivites/_collectiviteId/commune.vue, nuxt/pages/ddt/_departement/collectivites/_collectiviteId/epci.vue
This reverts commit 851830f8880cbdf4e98aef17209c077d6f982ba3.
=> Revert "Bandeau warning import Sudocuh en pause"

nuxt/pages/collectivites/_collectiviteId/procedures/add.vue
=> Form création procédure - Autorisation pour les admins

django/core/models.py, django/core/tests/test_models.py, django/core/tests/test_views.py, django/core/views.py
=> API périmètre - Expose type_document

nuxt/content/Dev/API/urba/perimetres.md
ref https://github.com/MTES-MCT/Docurba/issues/1181
=> API Périmètres - Corrige l'URL dans la documentation

nuxt/content/Dev/API/urba/scots.md
ref https://github.com/MTES-MCT/Docurba/issues/1252
=> Documente l'API Scot en Django

nuxt/plugins/daturba.js
ref https://github.com/MTES-MCT/Docurba/issues/1164
=> Change l'URL de l'API Datara

nuxt/components/Ddt/PerimeterCheckInput.vue, nuxt/components/Procedures/InsertForm.vue
En mettant le titre généré plus proche des champs qui l'affectent, on espère que cela améliorera la qualité des titres.
ref https://github.com/MTES-MCT/Docurba/issues/1303 ref https://github.com/MTES-MCT/Docurba/issues/1322
=> Création procédure - Mise en avant du titre généré

django/core/models.py, django/core/tests/manual_test_e2e.py, django/core/tests/test_models.py, django/core/tests/test_views.py, django/core/views.py
- Tests de la vue adaptés pour inclure une collectivité porteuse
ref https://github.com/MTES-MCT/Docurba/issues/1253
=> API Communes - Informations collectivité porteuse

django/core/models.py, django/core/tests/test_models.py, django/core/views.py, nuxt/content/Dev/API/communes.md
ref https://github.com/MTES-MCT/Docurba/issues/1253
=> API communes - Ajout des colonnes pluih et pdu_tient_lieu

nuxt/components/Layouts/BannerVacances.vue, nuxt/pages/collectivites/_collectiviteId.vue, nuxt/pages/ddt/_departement/collectivites/index.vue, nuxt/pages/ddt/_departement/pac.vue
This reverts commit 7f2fa9a5f61bfbdbaa80c62621997bdb0ad160d2. ref https://github.com/MTES-MCT/Docurba/issues/1397
=> Revert "Bannière pour les vacances d'été"
