pages/index.vue

Il était déjà inopérant à cause d'un bug dans `plugins/tally.js` mais il est préférable de le désactiver totalement au cas où on corrige le bug de `plugins/tally.js`.
Vu avec @Octaviedebs qui m'a [confirmé le souhait de ne pas le réactiver.](https://docurba.slack.com/archives/C03MM1AD199/p1731597344358149?thread_ts=1731575961.213599&cid=C03MM1AD199)

Désactive formulaire d'onboarding

---

daily_dump/steps/6-setPerimeterStatus.mjs

La parallélisation :
- causait des timeout
- ne me donnait pas confiance que tous les départements étaient traités (le log précédent s'arrêtait à `52/101`)

Import - Boucle simple pour MAJ de l'opposabilité

---

server-middleware/modules/pipedrive.js
server-middleware/pipedrive.js

Il n'est pas utilisé et nous avons maintenant 3 champs plus granulaires avec `write_frise`, `read` et `write`.
ref https://github.com/MTES-MCT/Docurba/issues/1007

Pipedrive - Suppression du champ "shared"

---

server-middleware/slack.js

Dans les les logs applicatifs, nous voyons que /notify/frp est toujours en timeout car elle ne renvoie pas de statut et réponse

Route API toujours en timeout

---

pages/frise/_procedureId/index.vue

En attendant la réponse de la base de données, nous affichions le message 404.
Bug introduit dans https://github.com/MTES-MCT/Docurba/pull/1020

Procédure - Affichage 404 après la réponse de la BDD

---

pages/ddt/_departement/collectivites/index.vue

Cela répare aussi le tri par Type qui ne fonctionnait pas sur tous les navigateurs.
Plutôt que d'écrire un customSort pour toutes les colonnes, on personnalise juste le sort de la colonne Nom. Et comme on n'utilise que le `code` pour trier, faisons en la valeur de la colonne Nom.
ref https://github.com/MTES-MCT/Docurba/issues/668

Mes collectivités - Tri par défaut corrigé

---

pages/ddt/_departement/procedures/index.vue

https://github.com/MTES-MCT/Docurba/pull/1111 a ajouté plus de types de documents mais n'a pas mis à jour le menu de filtrage.
En utilisant le même tableau, on s'assure que tous les types de documents font partie du menu.
ref https://github.com/MTES-MCT/Docurba/issues/653

Mes procédures - Tous les Types de Documents sont filtrables

---

plugins/utils.js
tests_e2e/test_titre_procedure.py

Il faut aussi regarder parmi les membres pour trouver la collectivité porteuse
Pour rendre le test E2E "Mes collectivités" plus robuste, on vérifie toutes les titres de procédures en les cherchant par le lien vers la frise.
fix https://github.com/MTES-MCT/Docurba/issues/1117

Corrige nom de procédure pour EPCI sans fiscalité propre

---

content/Dev/API/urba/communesCode.md
content/Dev/API/urba/perimetres.md
content/Dev/API/urba/scots.md

J'ai mis a jour la doc pour les exports communes, SCOT et perim. Elles sont disponible en public sur /dev/api --> https://docurba.beta.gouv.fr/dev/api

Documentation de l'API

---

components/Ddt/PerimeterCheckInput.vue

Pour les procédures secondaires, "communes concernées" pouvait laisser penser qu'il fallait n'en sélectionner qu'une quand il s'agit de rajouter ou enlever une commune au document d'urbanisme.

Création de procédure - Wording Périmètre

---

pages/frise/_procedureId/index.vue

Pour trouver les partages dans `projects_sharing`, il faut avoir un `project_id`. Donc remontons cette ligne.
Cassé par https://github.com/MTES-MCT/Docurba/commit/04523ea1b8e06b651051d895b859ba470bc65ef4
ref https://github.com/MTES-MCT/Docurba/issues/1080

Fix liste des collaborateurs procédure secondaire Docurba

---

components/Dashboard/DUItem.vue
tests_e2e/test_titre_procedure.py

https://github.com/MTES-MCT/Docurba/commit/d5b9f42da8edf4557bf6ad4913b53453ad71b4e3 a caché les procédures sans collectivité connue. L'intention était d'éviter des erreurs Vue tant que le fetch n'avait pas terminé. Plutôt que de tester que le fetch ait terminé, il vérifiait si `collectivite` avait une valeur.
On vérifie maintenant si le fetch est en attente.
ref https://github.com/MTES-MCT/Docurba/issues/792

Page collectivité - Affichons les procédures sans collectivité connue

---

nuxt/plugins/urbanisator.js

J'ai simplement rajouter un filtre front sur les procédures d'abrogations.
C'est la solution proposé par Hermance. Je trouve que c'est correcte puisque que comme tu as dis les abrogations ne sont pas compter dans les exports.
Ca semble corrigé correctement l'affichage dans les cas relevé dans l'issue.

Cache les procédures abrogées

---

nuxt/pages/ddt/_departement/pac.vue
nuxt/pages/trames/_githubRef.vue

Revert commits ee2b8d25b54d4b16fb33de47d00a6a7dca3f4e27 and c9b0bd44b050c3e40725fd6417f5767f2863fb4a.
fix https://github.com/MTES-MCT/Docurba/issues/1131

Transfert Repo PAC - Suppression du bandeau d'information

---

nuxt/components/Dashboard/DUProcedureItem.vue
nuxt/components/Dashboard/DUSubProcedureItem.vue
nuxt/pages/frise/_procedureId/index.vue

J'étais initialement partis sur un plugin qui faisait 2 opperations. Une première qui passe la procédure en soft delete. Puis une deuxième qui update le perimetre en opposable false.
Ca marchait bien mais en testant je me suis demander ce qu'il se passe si une des operations fail. Dans ce cas on se retrouve avec une incohérence entre les deux table.
J'aurais pu faire un trigger. Mais de nouveau on aurai eu du delay et ça revient au même pour la gestion d'erreur.
Du coup j'ai fais une function sql qui fait les deux opérations. Mais comme c'est dans une transaction. Si une des deux fail les changements ne seront pas pris en compte.
```sql
CREATE OR REPLACE FUNCTION soft_delete_procedure(deleted_procedure_id uuid)
RETURNS void LANGUAGE sql AS $$
-- Update procedures
UPDATE procedures
SET …
```

Passer les suppressions en soft_delete

---

nuxt/components/Frise/ShareDialog.vue
nuxt/components/Onboarding/SignupForm.vue
nuxt/pages/frise/_procedureId/index.vue
nuxt/pages/frise/_procedureId/invite.vue
nuxt/pages/login/collectivites/signup.vue
nuxt/plugins/utils.js

- Centralise la définition des postes et rôles dans un seul fichier
- Les rôles et postes sont identiques entre l'inscription et les affichages des collaborateurs.
- Sur la frise, les noms et intitulés ne sont plus tronqués
- "agence_urba" devient être "Agence d'urbanisme" [Exemple](https://docurba.beta.gouv.fr/frise/305024ef-0d8e-47ae-8251-77da6a9bd6a5)
- Enlève l'espace précédent la virgule entre le rôle et les postes "DDT , Suivi de procédure" 🤓
- Utilise le point médian
- Renomme "Employé de mairie" en "Technicien·ne ou employé·e"
- Enlève "Autre" [Exemple](https://docurba.beta.gouv.fr/frise/b0363148-3f86-4800-9bc2-890e05c891a3)
- Préfixe certains postes par "Collectivité, " [Exemple 1](https://docurba.beta.gouv.fr/frise/a52676e3-4368-4b07-b7e1-6425e0ce444a) [Exemple …

Remettre à plat les intitulés des rôles et postes

---

nuxt/server-middleware/trames.js

Toutes les autres actions d'écriture ne précisent pas de committer donc cela ne semble pas nécessaire.

PAC - Enlever Fabien comme committer

---

django/core/models.py
django/core/tests/test_models.py
django/core/tests/test_views.py
django/core/views.py
nuxt/content/Dev/API/urba/perimetres.md

fix https://github.com/MTES-MCT/Docurba/issues/1251

API périmètres - Limiter aux événements avant une date

---

nuxt/components/Frise/EventForm.vue
nuxt/components/VTextDatePicker.vue

Forçons les gens à choisir une date, car la date du jour n'est pas une bonne valeur par défaut. On rend aussi ce champ obligatoire.
fix https://github.com/MTES-MCT/Docurba/issues/1263

Form ajout d'event - Pas de date par défaut

---

nuxt/pages/ddt/_departement/procedures/index.vue

Le formattage est déplacé dans `mounted` car l'on ne devrait pas modifier de données dans `computed`.
ref https://github.com/MTES-MCT/Docurba/issues/1270

Mes Procédures - Formatte les dates de manière identique

---

django/core/admin.py
django/core/models.py
django/core/tests/test_models.py
django/core/tests/test_views.py

La colonne `is_principale` est redondante avec l'absence de valeur dans la colonne `secondary_procedure_of`.

DRY - Procedure.is_principale devient Procedure.parente

---

nuxt/pages/ddt/_departement/procedures/index.vue

Pour une raison que je ne comprends pas, on pouvait avoir une date qui inversait le jour et le mois ou des "Invalid date". Peut-être un partage d'objets sous-jacent.
En stockant la date formatée dans une nouvelle propriété, on évite de modifier la date originale. Ce qui rend plusieurs formattages idempotents.
fix https://github.com/MTES-MCT/Docurba/issues/791
fix https://github.com/MTES-MCT/Docurba/issues/1270

Mes Procédures - Affiche la date correcte pour les événements

---

django/Procfile

Le site Nuxt génère des URLs pour récupérer les informations de toutes les communes appartenant à un groupement. Pour les plus gros groupements, cela génère des URLs dépassant 4094 octets, [valeur par défaut de limit-request-line dans Gunicorn](https://docs.gunicorn.org/en/latest/settings.html#limit-request-line).
En attendant de remplacer par Django, on désactive cette limite. Cela pourrait faciliter un DDOS mais comme c'était le comportement avant l'introduction de Django, ce n'est pas un nouveau risque.
Problème introduit par https://github.com/MTES-MCT/Docurba/commit/f7614e8c
ref https://github.com/MTES-MCT/Docurba/issues/1237

Permet de consulter les pages d'un gros groupement

---

nuxt/pages/frise/_procedureId/index.vue
nuxt/plugins/sharing.js
nuxt/plugins/utils.js

Plutôt que de s'appuyer sur une liste statique et avec des règles arbitraires, utilisons une colonne dans la base de données.
Cela permet aussi d'afficher les collaborateurs de collectivités comme Hautes Terres ou La Teste De Buch (qui ont des emails contenant "test")
fix https://github.com/MTES-MCT/Docurba/issues/877

Collaborateurs FRP - Cache les comptes is_staff

---

django/core/models.py
django/core/tests/test_models.py

Comme nous n'avons actuellement pas de contraintes en base de données, il faut représenter cela dans notre modélisation.
Notamment, cela permet que `Procedure.objects.select_related('collectivite_porteuse')` utilise un `LEFT JOIN` plutôt que `INNER JOIN`

Lier les procédures à des collectivités inconnues au COG 2024

---

django/core/models.py
django/core/tests/factories.py
django/core/tests/manual_test_e2e.py
django/core/tests/test_models.py
django/core/tests/test_views.py
django/core/urls.py
django/core/views.py

- Pour les vues :
- Factorise le traitement de la querystring pour le paramètre "avant" entre les deux routes
- Ajoute la nouvelle route d'API
- Pour les Procédures :
- Lit la colonne existante `from_sudocuh`
- Ajoute `date_prescription` dans les queryset `Procedure.with_events()`
- Ajoute le concept d'EventNotable pour les dates notables à exporter
- Ajoute la méthode de queryset `Procedure.with_dates_notables()` pour inclure ces dates notables
- Ajoute la propriété `Procedure.is_interdepartemental`
- Pour les Collectivités :
- Ajoute une méthode de queryset `Collectivite.portant_scot()` pour retourner les collectivités portant un SCoT, avec toutes les données nécessaires
- Ajoute une méthode `scots_pour_csv` permettant de retourner les SCoT d'une collectivité dans le format attendu par …

API Scots en Django

---

nuxt/server-middleware/modules/admin.js
nuxt/server-middleware/modules/sharing.js
nuxt/server-middleware/slack.js

Le code existant retournait toujours une URL, que le compte ait une procédure partagée ou non. Il ne fonctionnait aussi pas si un compte avait plusieurs procédures qui lui avaient été partagées.
- Retourne undefined si un compte n'a eu aucune procédure partagée
- Sinon Retourne la procédure principale du projet associé au partage le plus récent
- Renomme la fonction pour mieux décrire ce qu'elle fait

Email validation compte reçoit la bonne procédure partagée

---

django/core/models.py
django/core/templates/collectivite.html
django/core/tests/factories.py
django/core/tests/manual_test_e2e.py
django/core/tests/test_models.py
django/core/tests/test_views.py
django/core/urls.py
django/core/views.py

- Lors de la comparaison avec l'API actuelle, nous avons remarqué que si un abandon et une prescription ont lieu le même jour, il est préférable que les Abandons gagnent sur les Prescriptions.
- Ajout des événements qui doivent être catégorisés et l'accesseur de leur date pour utilisation par le CSV.
- Modélisation des colonnes `Procedure.vaut_SCoT`, `Procedure.obligation_PDU` et `Procedure.maitrise_d_oeuvre`.
- Ajout de `delai_d_approbation`.
- Ajout de `Procedure.__lt__` pour centraliser le tri des procédures.
- Ajout de `Commune.is_nouvelle`, `Commune.procedures_principales_en_cours`, `Commune.plan_en_cours`
Tests :
- Ajout de `intercommunalite` et `is_nouvelle` à la factory `create_commune`
- `TestCommuneOpposabilite.test_ignore_event_apres()` utilise …

Premier jet de l'API communes

---

django/core/tests/factories.py

La factory `create_groupement()` pouvait créer des groupement avec un type de commune. Ces groupements faisaient donc parties des adhésions dans ViewCommuneAdhesionsDeep, faussant le décompte.
ref https://github.com/MTES-MCT/Docurba/issues/1253

Corrige tests instables impliquant ViewCommuneAdhesionsDeep

---

django/core/models.py
django/core/tests/manual_test_e2e.py
django/core/tests/test_models.py
django/core/views.py

- Lorsque le code_etat_complet d'une commune n'a pas de libellé, nous retournons un libellé vide mais loggons une exception pour collecter ces scénarios dans Sentry.
- Bien qu'il existe des POS que l'on devrait considérer en cours, on rajoute une logique spéciale pour ne pas le faire car cela interférait avec le libellé des code_etat_simple. Nous reverrons cette situation en travaillant sur https://github.com/MTES-MCT/Docurba/issues/1174.
ref https://github.com/MTES-MCT/Docurba/issues/1253

API communes - Codes état

---

django/core/models.py
django/core/tests/test_models.py
django/core/tests/test_views.py

Cela empêche de stocker des dates impossibles.
Cela occupe aussi moins de place sur le disque et en mémoire, côté SQL et Python. Cela réduit aussi le nombre de cast. Cela pourrait avoir des conséquences positives sur les performances.

Stocke la date d'un événement dans un type `date` SQL.

---

.github/workflows/lint_test.yml
django/core/models.py
django/core/tests/test_models.py
django/core/tests/test_views.py

- Ajoute `EventCategory.PUBLICATION_PERIMETRE` à la liste d'événements impactant le statut.
- Ajoute un événement valant `EventCategory.PUBLICATION_PERIMETRE`.
- Ajoute `Procedure.is_en_cours`. Cela regroupe les tests précédemment fait dans `Commune.procedures_principales_en_cours`, modifés pour ignorer les procédures sans PRESCRIPTION ou PUBLICATION_PERIMETRE.
- Utilise `Procedure.is_en_cours` pour déterminer les SCoTs en cours.
fix https://github.com/MTES-MCT/Docurba/issues/1174

API : Cache procédures sans évènement valant lancement

---

django/core/urls.py

Cela empêche le serveur de dev Nuxt de planter. Mais cela pollue la console du navigateur et la console de `runserver` donc une solution plus efficace serait appréciée.

Désactive le websocket hot reload Nuxt en dev

---

.mise.toml

Ces tâches permettent de démarrer les serveurs Nuxt et Django en une seule
commande ou séparement.

Mise: ajout de tâches pour démarrer les serveurs locaux

---

.github/workflows/lint_test.yml
django/core/settings.py

Un changement récent dans VSCode supprime la variable d'environnement
DEBUG au lancement de la commande Run Tests. Je n'ai pas trouvé de
meilleur moyen de contourner ce souci.
Cela étant, la variable d'environnement DJANGO_DEBUG est plus explicite
que simplement DEBUG et évite tout conflit éventuel avec d'autres
configurations.

Lire la variable d'environnement DJANGO_DEBUG

---

django/core/tests/manual_test_e2e.py
django/core/tests/test_views.py
django/core/urls.py

Cela évite de mettre à jour toutes les valeurs lors de leur changement.
Cela permet également de mieux identifier les applications auxquelles
sont intégrées les URL (avec des espaces de nom même si ce n'est pas
encore utile aujourd'hui puisque nous n'avons qu'une seule application).
https://docs.djangoproject.com/en/5.2/topics/http/urls/#reverse-resolution-of-urls
Pour l'instant, je n'ai touché qu'à la vue api_scots car c'est la seule
dont j'avais besoin pour la PR sur les zones blanches mais je pourrais
faire une passe sur les autres.

Faire référence au nom des URL au lieu de leur valeur
